#!/bin/csh

#
# Generated by basicFT2.com Version 2024.123.14.23
#
# basicFT2.com -in zero_freq_gauss.fid -ft1 zero_freq_gauss.ft1 \
#              -out zero_freq_gauss.ft2 

nmrPipe -in zero_freq_gauss.fid \
| nmrPipe -fn SP -off 0.5 -end 0.95 -pow 2 -elb 0.0 -glb 0.0 -c 0.5 \
| nmrPipe -fn ZF -zf 1 -auto \
| nmrPipe -fn FT -verb \
| nmrPipe -fn PS -p0 0.0 -p1 0.0 -di \
| nmrPipe -fn EXT -x1 0% -xn 100% -sw \
| nmrPipe -fn SAVE -name zero_freq_gauss.ft1 \
| nmrPipe -fn TP \
| nmrPipe -fn SP -off 0.5 -end 0.95 -pow 1 -elb 0.0 -glb 0.0 -c 0.5 \
| nmrPipe -fn ZF -zf 1 -auto \
| nmrPipe -fn FT -verb \
| nmrPipe -fn PS -p0 0.0 -p1 0.0 -di \
| nmrPipe -fn TP \
  -out zero_freq_gauss.ft2 -ov
